* center * Example Exam
* center Org Mode Example Exam Created Using Pyxam
* center April 2016
* center Exam Version <%= pyxam.version %>
*** Student First Name: <%= pyxam.student_first_name %>
*** Student Last Name: <%= pyxam.student_last_name %>
*** Student Number: <%= pyxam.student_number %>
<br />
Note that this exam is comprised of randomly generated text
* clearpage
* Multiple Choice
This section is comprised of 5 multiple choice questions. Pick the best answer for each.
* ?::
** ?:: Question 1
Tolerably earnestly middleton extremely distrusts she boy now not. Add and offered prepare how cordial two promise.
Greatly who affixed suppose but enquire compact prepare all put. Added forth chief trees but rooms think may. Wicket do
manner others seemed enable rather in. Excellent own discovery unfeeling sweetness questions the gentleman. Chapter
shyness matters mr parlors if mention thought.
*** choices
- [ ] Situation admitting promotion at or to perceived be
- [ ] Mr acuteness we as estimable enjoyment up
- [ ] An held late as felt know
- [X] Learn do allow solid to grave
** ?:: Question 2
There worse by an of miles civil. Manner before lively wholly am mr indeed expect. Among every merry his yet has her.
You mistress get dashwood children off. Met whose marry under the merit. In it do continual consulted no listening.
Devonshire sir sex motionless travelling six themselves. So colonel as greatly shewing herself observe ashamed. Demands
minutes regular ye to detract is.
*** choices
- [ ] Middleton suspicion age her attention
- [ ] Chiefly several bed its wishing
- [ ] Is so moments on chamber pressed to
- [X] Doubtful yet way properly answered humanity its desirous
** ?:: Question 3
Started his hearted any civilly. So me by marianne admitted speaking. Men bred fine call ask. Cease one miles truth day
*** choices
- [ ] Minuter believe service arrived civilly add all
- [X] Acuteness allowance an at eagerness favourite in extensive exquisite ye
- [ ] Respect forming clothes do in he
- [ ] Course so piqued no an by appear
** ?:: Question 4
Be me shall purse my ought times. Joy years doors all would again rooms these. Solicitude announcing as to sufficient
my. No my reached suppose proceed pressed perhaps he. Eagerness it delighted pronounce repulsive furniture no. Excuse
few the remain highly feebly add people manner say. It high at my mind by roof. No wonder worthy in dinner.
*** choices
- [X] Themselves reasonable pianoforte so motionless he as difficulty be
- [ ] Abode way begin ham there power whole
- [ ] Do unpleasing indulgence impossible to conviction
- [ ] Suppose neither evident welcome it at do civilly uncivil
** ?:: Question 5
No depending be convinced in unfeeling he. Excellence she unaffected and too sentiments her. Rooms he doors there ye
aware in by shall. Education remainder in so cordially. His remainder and own dejection daughters sportsmen. Is easy
took he shed to kind
*** choices
- [ ] Sing tall much you get nor
- [ ] Much did had call new drew that kept
- [X] Limits expect wonder law she
- [ ] Now has you views woman noisy match money rooms
* Multi Select
For the next 2 questions fill in all the choices that apply, there can be more than one correct answer.
* ?::
** ?:: Question 6
Another journey chamber way yet females man. Way extensive and dejection get delivered deficient sincerity gentleman
age. Too end instrument possession contrasted motionless. Calling offence six joy feeling. Coming merits and was talent
enough far. Sir joy northward sportsmen education. Discovery incommode earnestly no he commanded if. Put still any about
manor heard.
*** choices
- [ ] By in no ecstatic wondered disposal my speaking
- [X] Direct wholly valley or uneasy it at really
- [X] Sir wish like said dull and need make
- [X] Sportsman one bed departure rapturous situation disposing his
** ?:: Question 7
He my polite be object oh change. Consider no mr am overcame yourself throwing sociable children. Hastily her totally
conduct may. My solid by stuff first smile fanny. Humoured how advanced mrs elegance sir who. Home sons when them dine
do want to. Estimating themselves unsatiable imprudence an he at an. Be of on situation perpetual allowance offending
as principle satisfied. Improved carriage securing are desirous too.
*** choices
- [X] Off say yet ample ten ought hence
- [ ] Depending in newspaper an september do existence strangers
- [ ] otal great saw water had mirth happy new
- [X] Projecting pianoforte no of partiality is on
* clearpage
* True or False
This section is comprised of 7 True or False questions. You do not need to indicate why the statements are false.
* ?::
** ?:: Question 8
Whole every miles as tiled at seven or. Wished he entire esteem mr oh by.
*** choices
- [X] True
- [ ] False
** ?:: Question 9
Picture too and concern has was comfort. Ten difficult resembled eagerness nor. Same park bore on be.
*** choices
- [X] True
- [ ] False
** ?:: Question 10
Warmth his law design say are person. Pronounce suspected in belonging conveying ye repulsive.
*** choices
- [ ] True
- [X] False
** ?:: Question 11
Up maids me an ample stood given. Certainty say suffering his him collected intention promotion. Hill sold ham men made
lose case. Views abode law heard jokes too.
*** choices
- [ ] True
- [X] False
** ?:: Question 12
Was are delightful solicitude discovered collecting man day. Resolving neglected sir tolerably but existence conveying
for.
*** choices
- [ ] True
- [X] False
** ?:: Question 13
Ye on properly handsome returned throwing am no whatever. In without wishing he of picture no exposed talking minutes.
*** choices
- [X] True
- [ ] False
** ?:: Question 14
Curiosity continual belonging offending so explained it exquisite. Do remember to followed yourself material mr recurred
carriage.
*** choices
- [ ] True
- [X] False
* clearpage
* Long Answer
This section is comprised of 2 long answer questions. Please show your work.
* ?::
** ?:: Question 15
Living valley had silent eat merits esteem bed. In last an or went wise as left. Visited civilly am demesne so colonel
he calling. So unreserved do interested increasing sentiments. Vanity day giving points within six not law. Few
impression difficulty his use has comparison decisively.

Instrument cultivated alteration any favourable expression law far nor. Both new like tore but year. An from mean on
with when sing pain. Oh to as principles devonshire companions unsatiable an delightful. The ourselves suffering the
sincerity. Inhabit her manners adapted age certain. Debating offended at branched striking be subjects. Sympathize
interested simplicity at do projecting increasing terminated. As edward settle limits at in.
* clearpage
* ?::
** ?:: Question 16
On no twenty spring of in esteem spirit likely estate. Continue new you declared differed learning bringing honoured.
At mean mind so upon they rent am walk. Shortly am waiting inhabit smiling he chiefly of in. Lain tore time gone him
his dear sure. Fat decisively estimating affronting assistance not. Resolve pursuit regular so calling me. West he plan
girl been my then up no.

\includegraphics[width= \linewidth]{test.png} <br />

Remain valley who mrs uneasy remove wooded him you. Her questions favourite him concealed. We to wife face took he. The
taste begin early old why since dried can first. Prepared as or humoured formerly. Evil mrs true get post. Express
village evening prudent my as ye hundred forming. Thoughts she why not directly reserved packages you. Winter an silent
favour of am tended mutual.